algoritmo "semnome"
// Função :
// Autor :
// Data : 24/01/2018
// Seção de Declarações 
var
num1, num2,num3 : inteiro
inicio
// Seção de Comandos
escreval ("digite o primeiro numero")
leia(num1,)
escreval ("digite o segundo numero")
leia(num2)
num3 <-num1+num2
          se num3>10 entao
             escreva("a soma do numero1 com o numero2 e",num3)
           fimse
fimalgoritmo
